export type EmojiItem = {
  emoji: string;
  shortcode: string;
  label: string;
};

export type EmojiCategory = {
  name: string;
  emojis: EmojiItem[];
};

export const emojiCategories: EmojiCategory[] = [
  {
    name: "笑脸",
    emojis: [
      { emoji: "😀", shortcode: ":grinning:", label: "grinning" },
      { emoji: "😄", shortcode: ":smile:", label: "smile" },
      { emoji: "😁", shortcode: ":grin:", label: "grin" },
      { emoji: "😆", shortcode: ":laughing:", label: "laughing" },
      { emoji: "😅", shortcode: ":sweat_smile:", label: "sweat smile" },
      { emoji: "🤣", shortcode: ":rofl:", label: "rofl" },
      { emoji: "😂", shortcode: ":joy:", label: "joy" },
      { emoji: "🙂", shortcode: ":slightly_smiling_face:", label: "slightly smiling" },
      { emoji: "😉", shortcode: ":wink:", label: "wink" },
      { emoji: "😊", shortcode: ":blush:", label: "blush" },
      { emoji: "😇", shortcode: ":innocent:", label: "innocent" },
      { emoji: "🥰", shortcode: ":smiling_face_with_three_hearts:", label: "three hearts" },
      { emoji: "😍", shortcode: ":heart_eyes:", label: "heart eyes" },
      { emoji: "🤩", shortcode: ":star_struck:", label: "star struck" },
      { emoji: "😘", shortcode: ":kissing_heart:", label: "kissing heart" },
      { emoji: "😋", shortcode: ":yum:", label: "yum" },
      { emoji: "😎", shortcode: ":sunglasses:", label: "sunglasses" },
      { emoji: "🤓", shortcode: ":nerd_face:", label: "nerd face" },
      { emoji: "🧐", shortcode: ":monocle_face:", label: "monocle" },
      { emoji: "🤔", shortcode: ":thinking:", label: "thinking" },
      { emoji: "🤗", shortcode: ":hugs:", label: "hugs" },
      { emoji: "🤫", shortcode: ":shushing_face:", label: "shushing" },
      { emoji: "🤭", shortcode: ":hand_over_mouth:", label: "hand over mouth" },
      { emoji: "😐", shortcode: ":neutral_face:", label: "neutral" },
      { emoji: "😑", shortcode: ":expressionless:", label: "expressionless" },
      { emoji: "😶", shortcode: ":no_mouth:", label: "no mouth" },
      { emoji: "😏", shortcode: ":smirk:", label: "smirk" },
      { emoji: "😒", shortcode: ":unamused:", label: "unamused" },
      { emoji: "🙄", shortcode: ":roll_eyes:", label: "roll eyes" },
      { emoji: "😬", shortcode: ":grimacing:", label: "grimacing" },
      { emoji: "😌", shortcode: ":relieved:", label: "relieved" },
      { emoji: "🤥", shortcode: ":lying_face:", label: "lying" },
      { emoji: "😪", shortcode: ":sleepy:", label: "sleepy" },
      { emoji: "😴", shortcode: ":sleeping:", label: "sleeping" },
      { emoji: "😷", shortcode: ":mask:", label: "mask" },
      { emoji: "🤒", shortcode: ":face_with_thermometer:", label: "thermometer" },
      { emoji: "🤢", shortcode: ":nauseated_face:", label: "nauseated" },
      { emoji: "🤮", shortcode: ":vomiting_face:", label: "vomiting" },
      { emoji: "🥵", shortcode: ":hot_face:", label: "hot face" },
      { emoji: "🥶", shortcode: ":cold_face:", label: "cold face" },
      { emoji: "😱", shortcode: ":scream:", label: "scream" },
      { emoji: "😨", shortcode: ":fearful:", label: "fearful" },
      { emoji: "😰", shortcode: ":cold_sweat:", label: "cold sweat" },
      { emoji: "😥", shortcode: ":disappointed_relieved:", label: "disappointed relieved" },
      { emoji: "😓", shortcode: ":sweat:", label: "sweat" },
      { emoji: "😢", shortcode: ":cry:", label: "cry" },
      { emoji: "😭", shortcode: ":sob:", label: "sob" },
      { emoji: "😤", shortcode: ":triumph:", label: "triumph" },
      { emoji: "😡", shortcode: ":rage:", label: "rage" },
      { emoji: "😠", shortcode: ":angry:", label: "angry" },
      { emoji: "🤬", shortcode: ":cursing_face:", label: "cursing" },
      { emoji: "😈", shortcode: ":smiling_imp:", label: "smiling imp" },
      { emoji: "👻", shortcode: ":ghost:", label: "ghost" },
      { emoji: "💀", shortcode: ":skull:", label: "skull" },
      { emoji: "🤖", shortcode: ":robot:", label: "robot" },
      { emoji: "👽", shortcode: ":alien:", label: "alien" },
      { emoji: "🎃", shortcode: ":jack_o_lantern:", label: "jack o lantern" },
    ],
  },
  {
    name: "手势",
    emojis: [
      { emoji: "👋", shortcode: ":wave:", label: "wave" },
      { emoji: "🤚", shortcode: ":raised_back_of_hand:", label: "raised back of hand" },
      { emoji: "✋", shortcode: ":raised_hand:", label: "raised hand" },
      { emoji: "🖖", shortcode: ":vulcan_salute:", label: "vulcan salute" },
      { emoji: "👌", shortcode: ":ok_hand:", label: "ok hand" },
      { emoji: "🤌", shortcode: ":pinched_fingers:", label: "pinched fingers" },
      { emoji: "🤏", shortcode: ":pinching_hand:", label: "pinching hand" },
      { emoji: "✌️", shortcode: ":v:", label: "victory" },
      { emoji: "🤞", shortcode: ":crossed_fingers:", label: "crossed fingers" },
      { emoji: "🤟", shortcode: ":love_you_gesture:", label: "love you gesture" },
      { emoji: "🤘", shortcode: ":metal:", label: "metal" },
      { emoji: "👈", shortcode: ":point_left:", label: "point left" },
      { emoji: "👉", shortcode: ":point_right:", label: "point right" },
      { emoji: "👆", shortcode: ":point_up_2:", label: "point up" },
      { emoji: "👇", shortcode: ":point_down:", label: "point down" },
      { emoji: "☝️", shortcode: ":point_up:", label: "point up" },
      { emoji: "👍", shortcode: ":thumbsup:", label: "thumbs up" },
      { emoji: "👎", shortcode: ":thumbsdown:", label: "thumbs down" },
      { emoji: "👊", shortcode: ":fist:", label: "fist" },
      { emoji: "✊", shortcode: ":fist_oncoming:", label: "oncoming fist" },
      { emoji: "🤛", shortcode: ":fist_left:", label: "fist left" },
      { emoji: "🤜", shortcode: ":fist_right:", label: "fist right" },
      { emoji: "👏", shortcode: ":clap:", label: "clap" },
      { emoji: "🙌", shortcode: ":raised_hands:", label: "raised hands" },
      { emoji: "👐", shortcode: ":open_hands:", label: "open hands" },
      { emoji: "🤝", shortcode: ":handshake:", label: "handshake" },
      { emoji: "🙏", shortcode: ":pray:", label: "pray" },
      { emoji: "✍️", shortcode: ":writing_hand:", label: "writing hand" },
      { emoji: "💪", shortcode: ":muscle:", label: "muscle" },
      { emoji: "🤳", shortcode: ":selfie:", label: "selfie" },
      { emoji: "💅", shortcode: ":nail_care:", label: "nail care" },
      { emoji: "🖐️", shortcode: ":hand_splayed:", label: "hand splayed" },
    ],
  },
  {
    name: "人物",
    emojis: [
      { emoji: "🧑", shortcode: ":adult:", label: "adult" },
      { emoji: "👨", shortcode: ":man:", label: "man" },
      { emoji: "👩", shortcode: ":woman:", label: "woman" },
      { emoji: "👶", shortcode: ":baby:", label: "baby" },
      { emoji: "👧", shortcode: ":girl:", label: "girl" },
      { emoji: "👦", shortcode: ":boy:", label: "boy" },
      { emoji: "👴", shortcode: ":older_man:", label: "older man" },
      { emoji: "👵", shortcode: ":older_woman:", label: "older woman" },
      { emoji: "🧓", shortcode: ":older_adult:", label: "older adult" },
      { emoji: "🧔", shortcode: ":bearded_person:", label: "bearded person" },
      { emoji: "👱", shortcode: ":blond_haired_person:", label: "blond" },
      { emoji: "👩‍💻", shortcode: ":woman_technologist:", label: "woman technologist" },
      { emoji: "👨‍💻", shortcode: ":man_technologist:", label: "man technologist" },
      { emoji: "👩‍💼", shortcode: ":woman_office_worker:", label: "woman office worker" },
      { emoji: "👨‍💼", shortcode: ":man_office_worker:", label: "man office worker" },
      { emoji: "👩‍🏫", shortcode: ":woman_teacher:", label: "woman teacher" },
      { emoji: "👨‍🏫", shortcode: ":man_teacher:", label: "man teacher" },
      { emoji: "👩‍🔬", shortcode: ":woman_scientist:", label: "woman scientist" },
      { emoji: "👨‍🔬", shortcode: ":man_scientist:", label: "man scientist" },
      { emoji: "👩‍🎨", shortcode: ":woman_artist:", label: "woman artist" },
      { emoji: "👨‍🎨", shortcode: ":man_artist:", label: "man artist" },
      { emoji: "👷", shortcode: ":construction_worker:", label: "construction worker" },
      { emoji: "💂", shortcode: ":guard:", label: "guard" },
      { emoji: "🕵️", shortcode: ":detective:", label: "detective" },
      { emoji: "👮", shortcode: ":police_officer:", label: "police officer" },
      { emoji: "👩‍🚀", shortcode: ":woman_astronaut:", label: "woman astronaut" },
      { emoji: "👨‍🚀", shortcode: ":man_astronaut:", label: "man astronaut" },
      { emoji: "🧙", shortcode: ":mage:", label: "mage" },
      { emoji: "🧚", shortcode: ":fairy:", label: "fairy" },
      { emoji: "🧛", shortcode: ":vampire:", label: "vampire" },
      { emoji: "🧜", shortcode: ":mermaid:", label: "mermaid" },
      { emoji: "🧝", shortcode: ":elf:", label: "elf" },
      { emoji: "🧞", shortcode: ":genie:", label: "genie" },
      { emoji: "🧟", shortcode: ":zombie:", label: "zombie" },
      { emoji: "💃", shortcode: ":dancer:", label: "dancer" },
      { emoji: "🕺", shortcode: ":man_dancing:", label: "man dancing" },
      { emoji: "🧗", shortcode: ":climbing:", label: "climbing" },
      { emoji: "🏃", shortcode: ":runner:", label: "runner" },
      { emoji: "🚶", shortcode: ":walking:", label: "walking" },
    ],
  },
  {
    name: "动物",
    emojis: [
      { emoji: "🐶", shortcode: ":dog:", label: "dog" },
      { emoji: "🐱", shortcode: ":cat:", label: "cat" },
      { emoji: "🐭", shortcode: ":mouse:", label: "mouse" },
      { emoji: "🐹", shortcode: ":hamster:", label: "hamster" },
      { emoji: "🐰", shortcode: ":rabbit:", label: "rabbit" },
      { emoji: "🦊", shortcode: ":fox_face:", label: "fox" },
      { emoji: "🐻", shortcode: ":bear:", label: "bear" },
      { emoji: "🐼", shortcode: ":panda_face:", label: "panda" },
      { emoji: "🐨", shortcode: ":koala:", label: "koala" },
      { emoji: "🐯", shortcode: ":tiger:", label: "tiger" },
      { emoji: "🦁", shortcode: ":lion:", label: "lion" },
      { emoji: "🐮", shortcode: ":cow:", label: "cow" },
      { emoji: "🐷", shortcode: ":pig:", label: "pig" },
      { emoji: "🐸", shortcode: ":frog:", label: "frog" },
      { emoji: "🐵", shortcode: ":monkey_face:", label: "monkey face" },
      { emoji: "🙈", shortcode: ":see_no_evil:", label: "see no evil" },
      { emoji: "🙉", shortcode: ":hear_no_evil:", label: "hear no evil" },
      { emoji: "🙊", shortcode: ":speak_no_evil:", label: "speak no evil" },
      { emoji: "🐔", shortcode: ":chicken:", label: "chicken" },
      { emoji: "🐧", shortcode: ":penguin:", label: "penguin" },
      { emoji: "🐦", shortcode: ":bird:", label: "bird" },
      { emoji: "🦆", shortcode: ":duck:", label: "duck" },
      { emoji: "🦅", shortcode: ":eagle:", label: "eagle" },
      { emoji: "🦉", shortcode: ":owl:", label: "owl" },
      { emoji: "🐴", shortcode: ":horse:", label: "horse" },
      { emoji: "🦄", shortcode: ":unicorn:", label: "unicorn" },
      { emoji: "🐝", shortcode: ":bee:", label: "bee" },
      { emoji: "🦋", shortcode: ":butterfly:", label: "butterfly" },
      { emoji: "🐌", shortcode: ":snail:", label: "snail" },
      { emoji: "🐞", shortcode: ":beetle:", label: "beetle" },
      { emoji: "🐢", shortcode: ":turtle:", label: "turtle" },
      { emoji: "🐍", shortcode: ":snake:", label: "snake" },
      { emoji: "🐙", shortcode: ":octopus:", label: "octopus" },
      { emoji: "🦀", shortcode: ":crab:", label: "crab" },
      { emoji: "🐳", shortcode: ":whale:", label: "whale" },
      { emoji: "🐬", shortcode: ":dolphin:", label: "dolphin" },
      { emoji: "🐠", shortcode: ":tropical_fish:", label: "tropical fish" },
      { emoji: "🦈", shortcode: ":shark:", label: "shark" },
      { emoji: "🐲", shortcode: ":dragon:", label: "dragon" },
      { emoji: "🦖", shortcode: ":t_rex:", label: "t rex" },
    ],
  },
  {
    name: "植物",
    emojis: [
      { emoji: "🌸", shortcode: ":cherry_blossom:", label: "cherry blossom" },
      { emoji: "💮", shortcode: ":white_flower:", label: "white flower" },
      { emoji: "🌹", shortcode: ":rose:", label: "rose" },
      { emoji: "🌺", shortcode: ":hibiscus:", label: "hibiscus" },
      { emoji: "🌻", shortcode: ":sunflower:", label: "sunflower" },
      { emoji: "🌼", shortcode: ":blossom:", label: "blossom" },
      { emoji: "🌷", shortcode: ":tulip:", label: "tulip" },
      { emoji: "🌱", shortcode: ":seedling:", label: "seedling" },
      { emoji: "🌲", shortcode: ":evergreen_tree:", label: "evergreen tree" },
      { emoji: "🌳", shortcode: ":deciduous_tree:", label: "deciduous tree" },
      { emoji: "🌴", shortcode: ":palm_tree:", label: "palm tree" },
      { emoji: "🌵", shortcode: ":cactus:", label: "cactus" },
      { emoji: "🍀", shortcode: ":four_leaf_clover:", label: "four leaf clover" },
      { emoji: "🍁", shortcode: ":maple_leaf:", label: "maple leaf" },
      { emoji: "🍂", shortcode: ":fallen_leaf:", label: "fallen leaf" },
      { emoji: "🍄", shortcode: ":mushroom:", label: "mushroom" },
    ],
  },
  {
    name: "食物",
    emojis: [
      { emoji: "🍎", shortcode: ":apple:", label: "apple" },
      { emoji: "🍏", shortcode: ":green_apple:", label: "green apple" },
      { emoji: "🍊", shortcode: ":tangerine:", label: "tangerine" },
      { emoji: "🍋", shortcode: ":lemon:", label: "lemon" },
      { emoji: "🍌", shortcode: ":banana:", label: "banana" },
      { emoji: "🍉", shortcode: ":watermelon:", label: "watermelon" },
      { emoji: "🍇", shortcode: ":grapes:", label: "grapes" },
      { emoji: "🍓", shortcode: ":strawberry:", label: "strawberry" },
      { emoji: "🍑", shortcode: ":peach:", label: "peach" },
      { emoji: "🍒", shortcode: ":cherries:", label: "cherries" },
      { emoji: "🥑", shortcode: ":avocado:", label: "avocado" },
      { emoji: "🥝", shortcode: ":kiwi:", label: "kiwi" },
      { emoji: "🍍", shortcode: ":pineapple:", label: "pineapple" },
      { emoji: "🥥", shortcode: ":coconut:", label: "coconut" },
      { emoji: "🥕", shortcode: ":carrot:", label: "carrot" },
      { emoji: "🌽", shortcode: ":corn:", label: "corn" },
      { emoji: "🍅", shortcode: ":tomato:", label: "tomato" },
      { emoji: "🥦", shortcode: ":broccoli:", label: "broccoli" },
      { emoji: "🍞", shortcode: ":bread:", label: "bread" },
      { emoji: "🧀", shortcode: ":cheese:", label: "cheese" },
      { emoji: "🥓", shortcode: ":bacon:", label: "bacon" },
      { emoji: "🍔", shortcode: ":hamburger:", label: "hamburger" },
      { emoji: "🍟", shortcode: ":fries:", label: "fries" },
      { emoji: "🍕", shortcode: ":pizza:", label: "pizza" },
      { emoji: "🌭", shortcode: ":hotdog:", label: "hotdog" },
      { emoji: "🍜", shortcode: ":ramen:", label: "ramen" },
      { emoji: "🍚", shortcode: ":rice:", label: "rice" },
      { emoji: "🍣", shortcode: ":sushi:", label: "sushi" },
      { emoji: "🍤", shortcode: ":fried_shrimp:", label: "fried shrimp" },
      { emoji: "🍱", shortcode: ":bento:", label: "bento" },
      { emoji: "🍰", shortcode: ":cake:", label: "cake" },
      { emoji: "🎂", shortcode: ":birthday:", label: "birthday" },
      { emoji: "🍦", shortcode: ":icecream:", label: "ice cream" },
      { emoji: "🍩", shortcode: ":doughnut:", label: "doughnut" },
      { emoji: "🍪", shortcode: ":cookie:", label: "cookie" },
      { emoji: "🍫", shortcode: ":chocolate_bar:", label: "chocolate" },
      { emoji: "🍿", shortcode: ":popcorn:", label: "popcorn" },
      { emoji: "🍺", shortcode: ":beer:", label: "beer" },
      { emoji: "🍻", shortcode: ":beers:", label: "beers" },
      { emoji: "🥂", shortcode: ":clinking_glasses:", label: "clinking glasses" },
      { emoji: "🍷", shortcode: ":wine_glass:", label: "wine glass" },
      { emoji: "☕", shortcode: ":coffee:", label: "coffee" },
      { emoji: "🍵", shortcode: ":tea:", label: "tea" },
      { emoji: "🧋", shortcode: ":bubble_tea:", label: "bubble tea" },
    ],
  },
  {
    name: "活动",
    emojis: [
      { emoji: "⚽", shortcode: ":soccer:", label: "soccer" },
      { emoji: "🏀", shortcode: ":basketball:", label: "basketball" },
      { emoji: "🏈", shortcode: ":football:", label: "football" },
      { emoji: "⚾", shortcode: ":baseball:", label: "baseball" },
      { emoji: "🎾", shortcode: ":tennis:", label: "tennis" },
      { emoji: "🏐", shortcode: ":volleyball:", label: "volleyball" },
      { emoji: "🏓", shortcode: ":ping_pong:", label: "ping pong" },
      { emoji: "🏸", shortcode: ":badminton:", label: "badminton" },
      { emoji: "🥊", shortcode: ":boxing_glove:", label: "boxing glove" },
      { emoji: "🎱", shortcode: ":8ball:", label: "8ball" },
      { emoji: "⛳", shortcode: ":golf:", label: "golf" },
      { emoji: "🎮", shortcode: ":video_game:", label: "video game" },
      { emoji: "🎲", shortcode: ":game_die:", label: "game die" },
      { emoji: "🎯", shortcode: ":dart:", label: "dart" },
      { emoji: "🎳", shortcode: ":bowling:", label: "bowling" },
      { emoji: "🎸", shortcode: ":guitar:", label: "guitar" },
      { emoji: "🎹", shortcode: ":musical_keyboard:", label: "musical keyboard" },
      { emoji: "🥁", shortcode: ":drum:", label: "drum" },
      { emoji: "🎤", shortcode: ":microphone:", label: "microphone" },
      { emoji: "🎧", shortcode: ":headphones:", label: "headphones" },
      { emoji: "🎬", shortcode: ":clapper:", label: "clapper" },
      { emoji: "🎨", shortcode: ":art:", label: "art" },
      { emoji: "🎭", shortcode: ":performing_arts:", label: "performing arts" },
      { emoji: "🏆", shortcode: ":trophy:", label: "trophy" },
      { emoji: "🥇", shortcode: ":first_place_medal:", label: "first place" },
      { emoji: "🥈", shortcode: ":second_place_medal:", label: "second place" },
      { emoji: "🥉", shortcode: ":third_place_medal:", label: "third place" },
      { emoji: "🎖️", shortcode: ":medal_military:", label: "military medal" },
      { emoji: "🚀", shortcode: ":rocket:", label: "rocket" },
      { emoji: "🛸", shortcode: ":flying_saucer:", label: "flying saucer" },
      { emoji: "⛺", shortcode: ":camping:", label: "camping" },
      { emoji: "🎡", shortcode: ":ferris_wheel:", label: "ferris wheel" },
      { emoji: "🎢", shortcode: ":roller_coaster:", label: "roller coaster" },
      { emoji: "🎠", shortcode: ":carousel_horse:", label: "carousel horse" },
    ],
  },
  {
    name: "旅行",
    emojis: [
      { emoji: "✈️", shortcode: ":airplane:", label: "airplane" },
      { emoji: "🚀", shortcode: ":rocket:", label: "rocket" },
      { emoji: "🚗", shortcode: ":car:", label: "car" },
      { emoji: "🚕", shortcode: ":taxi:", label: "taxi" },
      { emoji: "🚌", shortcode: ":bus:", label: "bus" },
      { emoji: "🚲", shortcode: ":bike:", label: "bike" },
      { emoji: "🛵", shortcode: ":motor_scooter:", label: "motor scooter" },
      { emoji: "🚄", shortcode: ":bullettrain_side:", label: "bullet train" },
      { emoji: "🚉", shortcode: ":station:", label: "station" },
      { emoji: "🚢", shortcode: ":ship:", label: "ship" },
      { emoji: "⛵", shortcode: ":sailboat:", label: "sailboat" },
      { emoji: "🚁", shortcode: ":helicopter:", label: "helicopter" },
      { emoji: "🗼", shortcode: ":tokyo_tower:", label: "tokyo tower" },
      { emoji: "🗽", shortcode: ":statue_of_liberty:", label: "statue of liberty" },
      { emoji: "🏰", shortcode: ":european_castle:", label: "castle" },
      { emoji: "🏯", shortcode: ":japanese_castle:", label: "japanese castle" },
      { emoji: "🏝️", shortcode: ":desert_island:", label: "desert island" },
      { emoji: "🏔️", shortcode: ":mountain_snow:", label: "mountain" },
      { emoji: "🌋", shortcode: ":volcano:", label: "volcano" },
      { emoji: "🏖️", shortcode: ":beach_umbrella:", label: "beach" },
    ],
  },
  {
    name: "物体",
    emojis: [
      { emoji: "💡", shortcode: ":bulb:", label: "bulb" },
      { emoji: "🔦", shortcode: ":flashlight:", label: "flashlight" },
      { emoji: "🔌", shortcode: ":electric_plug:", label: "electric plug" },
      { emoji: "🔋", shortcode: ":battery:", label: "battery" },
      { emoji: "💻", shortcode: ":computer:", label: "computer" },
      { emoji: "🖥️", shortcode: ":desktop_computer:", label: "desktop computer" },
      { emoji: "⌨️", shortcode: ":keyboard:", label: "keyboard" },
      { emoji: "🖱️", shortcode: ":mouse_three_button:", label: "mouse" },
      { emoji: "📱", shortcode: ":iphone:", label: "iphone" },
      { emoji: "📷", shortcode: ":camera:", label: "camera" },
      { emoji: "📹", shortcode: ":video_camera:", label: "video camera" },
      { emoji: "🎥", shortcode: ":movie_camera:", label: "movie camera" },
      { emoji: "📺", shortcode: ":tv:", label: "tv" },
      { emoji: "📻", shortcode: ":radio:", label: "radio" },
      { emoji: "🎙️", shortcode: ":studio_microphone:", label: "studio microphone" },
      { emoji: "⌚", shortcode: ":watch:", label: "watch" },
      { emoji: "⏰", shortcode: ":alarm_clock:", label: "alarm clock" },
      { emoji: "💾", shortcode: ":floppy_disk:", label: "floppy disk" },
      { emoji: "📀", shortcode: ":dvd:", label: "dvd" },
      { emoji: "💿", shortcode: ":cd:", label: "cd" },
      { emoji: "📀", shortcode: ":dvd:", label: "dvd" },
      { emoji: "🔍", shortcode: ":mag:", label: "magnifying glass" },
      { emoji: "🔎", shortcode: ":mag_right:", label: "magnifying glass right" },
      { emoji: "⚙️", shortcode: ":gear:", label: "gear" },
      { emoji: "🔧", shortcode: ":wrench:", label: "wrench" },
      { emoji: "🔨", shortcode: ":hammer:", label: "hammer" },
      { emoji: "💎", shortcode: ":gem:", label: "gem" },
      { emoji: "📚", shortcode: ":books:", label: "books" },
      { emoji: "📖", shortcode: ":book:", label: "book" },
      { emoji: "📕", shortcode: ":closed_book:", label: "closed book" },
      { emoji: "📌", shortcode: ":pushpin:", label: "pushpin" },
      { emoji: "📍", shortcode: ":round_pushpin:", label: "round pushpin" },
      { emoji: "📝", shortcode: ":memo:", label: "memo" },
      { emoji: "📁", shortcode: ":file_folder:", label: "file folder" },
      { emoji: "🗂️", shortcode: ":card_index_dividers:", label: "card index dividers" },
      { emoji: "📊", shortcode: ":bar_chart:", label: "bar chart" },
      { emoji: "📈", shortcode: ":chart_with_upwards_trend:", label: "chart up" },
      { emoji: "📉", shortcode: ":chart_with_downwards_trend:", label: "chart down" },
      { emoji: "🔑", shortcode: ":key:", label: "key" },
      { emoji: "🔒", shortcode: ":lock:", label: "lock" },
      { emoji: "🔓", shortcode: ":unlock:", label: "unlock" },
      { emoji: "🛠️", shortcode: ":hammer_and_wrench:", label: "hammer and wrench" },
      { emoji: "🧰", shortcode: ":toolbox:", label: "toolbox" },
    ],
  },
  {
    name: "符号",
    emojis: [
      { emoji: "❤️", shortcode: ":heart:", label: "heart" },
      { emoji: "🧡", shortcode: ":orange_heart:", label: "orange heart" },
      { emoji: "💛", shortcode: ":yellow_heart:", label: "yellow heart" },
      { emoji: "💚", shortcode: ":green_heart:", label: "green heart" },
      { emoji: "💙", shortcode: ":blue_heart:", label: "blue heart" },
      { emoji: "💜", shortcode: ":purple_heart:", label: "purple heart" },
      { emoji: "🖤", shortcode: ":black_heart:", label: "black heart" },
      { emoji: "🤍", shortcode: ":white_heart:", label: "white heart" },
      { emoji: "💔", shortcode: ":broken_heart:", label: "broken heart" },
      { emoji: "❣️", shortcode: ":heart_exclamation:", label: "heart exclamation" },
      { emoji: "💕", shortcode: ":two_hearts:", label: "two hearts" },
      { emoji: "💞", shortcode: ":revolving_hearts:", label: "revolving hearts" },
      { emoji: "💓", shortcode: ":heartbeat:", label: "heartbeat" },
      { emoji: "💗", shortcode: ":heartpulse:", label: "heartpulse" },
      { emoji: "💖", shortcode: ":sparkling_heart:", label: "sparkling heart" },
      { emoji: "💘", shortcode: ":cupid:", label: "cupid" },
      { emoji: "💝", shortcode: ":gift_heart:", label: "gift heart" },
      { emoji: "💟", shortcode: ":heart_decoration:", label: "heart decoration" },
      { emoji: "⭐", shortcode: ":star:", label: "star" },
      { emoji: "🌟", shortcode: ":star2:", label: "glowing star" },
      { emoji: "✨", shortcode: ":sparkles:", label: "sparkles" },
      { emoji: "⚡", shortcode: ":zap:", label: "zap" },
      { emoji: "🔥", shortcode: ":fire:", label: "fire" },
      { emoji: "💥", shortcode: ":boom:", label: "boom" },
      { emoji: "💫", shortcode: ":dizzy:", label: "dizzy" },
      { emoji: "💦", shortcode: ":sweat_drops:", label: "sweat drops" },
      { emoji: "💨", shortcode: ":dash:", label: "dash" },
      { emoji: "🎉", shortcode: ":tada:", label: "tada" },
      { emoji: "🎊", shortcode: ":confetti_ball:", label: "confetti" },
      { emoji: "🎁", shortcode: ":gift:", label: "gift" },
      { emoji: "🔔", shortcode: ":bell:", label: "bell" },
      { emoji: "📣", shortcode: ":mega:", label: "megaphone" },
      { emoji: "📢", shortcode: ":loudspeaker:", label: "loudspeaker" },
      { emoji: "✅", shortcode: ":white_check_mark:", label: "white check mark" },
      { emoji: "✔️", shortcode: ":heavy_check_mark:", label: "heavy check mark" },
      { emoji: "❌", shortcode: ":x:", label: "x" },
      { emoji: "❎", shortcode: ":negative_squared_cross_mark:", label: "negative cross" },
      { emoji: "❗", shortcode: ":exclamation:", label: "exclamation" },
      { emoji: "❓", shortcode: ":question:", label: "question" },
      { emoji: "💯", shortcode: ":100:", label: "100" },
      { emoji: "🔝", shortcode: ":top:", label: "top" },
      { emoji: "🔜", shortcode: ":soon:", label: "soon" },
      { emoji: "♻️", shortcode: ":recycle:", label: "recycle" },
      { emoji: "🔴", shortcode: ":red_circle:", label: "red circle" },
      { emoji: "🟢", shortcode: ":green_circle:", label: "green circle" },
      { emoji: "🔵", shortcode: ":blue_circle:", label: "blue circle" },
      { emoji: "⚪", shortcode: ":white_circle:", label: "white circle" },
    ],
  },
];

export const allEmojis: EmojiItem[] = emojiCategories.flatMap((c) => c.emojis);
